# HW4 Support Vector Machine and Decision Trees

# Due on 11/25 23:59 pm

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

## We will use the same affair dataset from HW3, but will skip the EDA phrase we have done enough of it

#### Everything removing outliers, create dummies variabes had been done for you

In [2]:
# Remember the affair data set from HW3, we will use that dataset again
# but we will directly load it from the API
orig_df = pd.read_csv("affairs2.csv")
# Set up our target class label
orig_df['had_affair'] = orig_df['affairs'].apply(lambda x: 1 if x != 0 else 0)
orig_df = orig_df.drop('affairs',axis=1)
# remove NA
orig_df.dropna(inplace=True)
# create dummies variable for occupation
occ = pd.get_dummies(orig_df['occupation'],drop_first=True)
# we include rate_marriage feature as well. In HW3, we did not include that variable
features = ['rate_marriage','age','yrs_married','children','religious','educ', 'had_affair']
df = orig_df
df = pd.concat([orig_df[features], occ], axis=1)
df.head()

rate_marriage   age  yrs_married  children  religious  educ  had_affair  \
0            3.0  32.0          9.0       3.0        3.0  17.0           1   
1            3.0  27.0         13.0       3.0        1.0  14.0           1   
2            4.0  22.0          2.5       0.0        1.0  16.0           1   
3            4.0  37.0         16.5       4.0        3.0  16.0           1   
4            5.0  27.0          9.0       1.0        1.0  14.0           1   

   occ2  occ3  occ4  occ5  occ6  
0     1     0     0     0     0  
1     0     1     0     0     0  
2     0     1     0     0     0  
3     0     0     0     1     0  
4     0     1     0     0     0

In [3]:
# make sure there is no missing values
df.isnull().sum()

rate_marriage    0
age              0
yrs_married      0
children         0
religious        0
educ             0
had_affair       0
occ2             0
occ3             0
occ4             0
occ5             0
occ6             0
dtype: int64

### Now we are ready to build models

### Question 1: Build a classification model using SVC using linear kernel with usual steps

In [4]:
#import the model from sklearn import svm, create the SVC object 
#model = svm.SVC()
#Call Train test split
#print out model performance

In [5]:
from sklearn.model_selection import train_test_split

In [8]:
from sklearn import svm
model = svm.SVC(kernel='linear')
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [9]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[803  56]
 [295 120]]
             precision    recall  f1-score   support

          0       0.73      0.93      0.82       859
          1       0.68      0.29      0.41       415

avg / total       0.72      0.72      0.69      1274

0.724489795918


### Question 2. Now try different value of C-parameter and rerun your model

In [16]:
from sklearn import svm
model = svm.SVC(kernel='linear', C=2.0)
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train, y_train)

SVC(C=2.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[796  51]
 [301 126]]
             precision    recall  f1-score   support

          0       0.73      0.94      0.82       847
          1       0.71      0.30      0.42       427

avg / total       0.72      0.72      0.68      1274

0.723704866562


### Question 3. Try using rbf as your kernel and use Gamma of 2**-5, 0.1, 1 and 2

In [20]:
from sklearn import svm
model = svm.SVC(kernel='rbf', gamma=2**-5)
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.03125, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[800  68]
 [292 114]]
             precision    recall  f1-score   support

          0       0.73      0.92      0.82       868
          1       0.63      0.28      0.39       406

avg / total       0.70      0.72      0.68      1274

0.717425431711


In [22]:
from sklearn import svm
model = svm.SVC(kernel='rbf', gamma=0.1)
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[801  78]
 [257 138]]
             precision    recall  f1-score   support

          0       0.76      0.91      0.83       879
          1       0.64      0.35      0.45       395

avg / total       0.72      0.74      0.71      1274

0.73704866562


In [24]:
from sklearn import svm
model = svm.SVC(kernel='rbf', gamma=1)
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [25]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[758  96]
 [299 121]]
             precision    recall  f1-score   support

          0       0.72      0.89      0.79       854
          1       0.56      0.29      0.38       420

avg / total       0.66      0.69      0.66      1274

0.689952904239


In [26]:
from sklearn import svm
model = svm.SVC(kernel='rbf', gamma=2)
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=2, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [27]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[765  93]
 [350  66]]
             precision    recall  f1-score   support

          0       0.69      0.89      0.78       858
          1       0.42      0.16      0.23       416

avg / total       0.60      0.65      0.60      1274

0.652276295133


### Question 4. So out of all the models you try in Question 3 and 4, what is the best choice for the kernel, C and gamma parameters?

***Kernel='rbf', C=1.0, gamma=0.1***

# Now we will try to fit the same dataset with Decision Trees

### Question 5. Build a Decision Tree Classifier using default parameter

In [28]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [29]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[692 178]
 [228 176]]
             precision    recall  f1-score   support

          0       0.75      0.80      0.77       870
          1       0.50      0.44      0.46       404

avg / total       0.67      0.68      0.68      1274

0.681318681319


### Question 6. Now try using max_depth = 2, 3, 4 and crierion = 'gini' and 'entropy' to build 3 X 2 = 6 different models

In [38]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=2, criterion='gini')
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[805  69]
 [281 119]]
             precision    recall  f1-score   support

          0       0.74      0.92      0.82       874
          1       0.63      0.30      0.40       400

avg / total       0.71      0.73      0.69      1274

0.725274725275


In [39]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=3, criterion='gini')
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[815  76]
 [249 134]]
             precision    recall  f1-score   support

          0       0.77      0.91      0.83       891
          1       0.64      0.35      0.45       383

avg / total       0.73      0.74      0.72      1274

0.744897959184


In [40]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=4, criterion='gini')
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[814  57]
 [270 133]]
             precision    recall  f1-score   support

          0       0.75      0.93      0.83       871
          1       0.70      0.33      0.45       403

avg / total       0.73      0.74      0.71      1274

0.743328100471


In [41]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=2, criterion='entropy')
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[814  86]
 [252 122]]
             precision    recall  f1-score   support

          0       0.76      0.90      0.83       900
          1       0.59      0.33      0.42       374

avg / total       0.71      0.73      0.71      1274

0.734693877551


In [42]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=3, criterion='entropy')
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[779  74]
 [305 116]]
             precision    recall  f1-score   support

          0       0.72      0.91      0.80       853
          1       0.61      0.28      0.38       421

avg / total       0.68      0.70      0.66      1274

0.70251177394


In [43]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=4, criterion='entropy')
X = df.drop('had_affair', axis=1)
y = df['had_affair']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model.fit(X_train,y_train)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))

[[781  88]
 [273 132]]
             precision    recall  f1-score   support

          0       0.74      0.90      0.81       869
          1       0.60      0.33      0.42       405

avg / total       0.70      0.72      0.69      1274

0.716640502355


### Question 7. What is your obsevation from Question 6? Does the choice of the criterion important in this case? What about the max_depth? What is the best choice of max_depth and criterion?

***No, the criterion is not important. The max_depth is important. The best choice for max_depth is 3 and criterion is gini***

## Tree Visualization

Scikit learn actually has some built-in visualization capabilities for decision trees, you won't use this often and it requires you to install the pydot library, but here is an example of what it looks like and the code to execute this:

In [45]:
from IPython.display import Image  
from sklearn.externals.six import StringIO  
from sklearn.tree import export_graphviz
import io
import pydot 

features = list(df.columns[1:])
features

['age',
 'yrs_married',
 'children',
 'religious',
 'educ',
 'had_affair',
 'occ2',
 'occ3',
 'occ4',
 'occ5',
 'occ6']

In [46]:
dot_data = StringIO()  
export_graphviz(model, out_file=dot_data, feature_names=features)
(graph, ) = pydot.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

FileNotFoundError: [Errno 2] "dot" not found in path.

### Question 8, now pick three models, with max_depth = 2, 3 and 4. You can pick the which ever criterions you want and visual the three trees

Type your code here

In [23]:
# Hint 
# model1 = DecisionTreeClassifier(max_depth=..., criterion= ...)
# model1.fit(X_train, y_train)
# model2 = DecisionTreeClassifier(max_depth=..., criterion= ...)
# model2.fit(X_train, y_train)
# model3 = DecisionTreeClassifier(max_depth=..., criterion= ...)
# model3.fit(X_train, y_train)
# Then display all 3 trees
# 

#dot_data = StringIO()  
#export_graphviz(model1, out_file=dot_data, feature_names=features)
#graph = pydot.graph_from_dot_data(dot_data.getvalue())
#Image(graph[0].create_png())

### Question 9. Now build a Random Forest Classifier with, say, 100 trees. Check the model performance 

Type your code here